#!/bin/bash

usage="Usage: dtc [ info | stake | latest | dust ] \n \n
	info: Check basic info. \n
	stake: Enables staking; Passes password without storing it in memory. \n
	latest: Compares latest block with the DuticoinNL hosted block explorer. \n
	dust: Prunes dust from wallet. Dust is defined as less than .0001DTC. Requires jq. \n"

dtcc='/usr/local/bin/duticoin-cli -datadir=/var/lib/.duticoin/'

case $1 in

info )
	$dtcc getwalletinfo | egrep "balance|staked_balance|txcount|unconfirmed_balance|immature_balance|total_balance";
	$dtcc getnetworkinfo | egrep "subversion|connections";
	$dtcc getinfo | egrep "blocks";
	$dtcc getblockchaininfo | egrep "best";
	$dtcc getstakinginfo | egrep "enabled|staking|netstakeweight|expectedtime";
;;	

stake )
	echo 'enter Duticoin Password'
	read -s DTCPW
	$dtcc walletpassphrase $DTCPW 99999999 true
	DTCPW=null
;;

latest )
	latest=$($dtcc  getblockcount) && \
	    blacksight=$(curl -s https://node.duticoin.io/insight-api/block-index/$latest? |  cut -d '"' -f4) && \
	    duticoin=$($dtcc  getblockhash $latest) && \
	    diff -sy --label Local <(echo $duticoin) --label Explorer <(echo $blacksight)
;;

dust )
	IFS=$'\n';

	 /usr/local/bin/duticoin-cli -datadir=/var/lib/.duticoin/ listtransactions "*" 99999 | jq -r '.[] | select(.category != "send") | select(.amount < .0001) | .txid' | uniq >txid.txt

	while read line; do
	        echo $line 
	        /usr/local/bin/duticoin-cli -datadir=/var/lib/.duticoin/ removeprunedfunds $(echo $line)
	done < "txid.txt"
;;

*)
    echo -e $usage
;;	

esac
